spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: msbox8-service
          uri: lb://MSBOX8-SERVICE
          predicates:
            - Path=/box8/**
          filters:
            - AuthenticationFilter

        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
          route:
            RouteDefinitionRouteLocator: INFO
#    org:
#    springframework:
#        cloud:
#          gateway: TRACE
#          route:
#            RouteDefinitionRouteLocator: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka